CREATE TABLE Fornecedor (
    FornecedorID INT PRIMARY KEY,
    NomeFornecedor VARCHAR(100) NOT NULL,
    Contato VARCHAR(50),
    Endereço VARCHAR(200)
);

-- Tabela Produto
CREATE TABLE Produto (
    CódigoProduto INT PRIMARY KEY,
    Nome VARCHAR(100) NOT NULL,
    Preço DECIMAL(10, 2) NOT NULL,
    QuantidadeEstoque INT NOT NULL,
    Categoria VARCHAR(50),
    FornecedorID INT,
    FOREIGN KEY (FornecedorID) REFERENCES Fornecedor(FornecedorID)
        ON DELETE SET NULL ON UPDATE CASCADE
);

-- Tabela Colaborador
CREATE TABLE Colaborador (
    ColaboradorID INT PRIMARY KEY,
    Nome VARCHAR(100) NOT NULL,
    Cargo VARCHAR(50),
    HorarioTrabalho VARCHAR(20),
    Salario DECIMAL(10, 2) NOT NULL,
    Contato VARCHAR(50),
    HorasTrabalhadas INT
);

-- Tabela Cliente
CREATE TABLE Cliente (
    ClienteID INT PRIMARY KEY,
    Nome VARCHAR(100) NOT NULL,
    Endereço VARCHAR(200),
    Email VARCHAR(100),
    Telefone VARCHAR(20),
    HistoricoCompras TEXT,
    PontosFidelidade INT DEFAULT 0
);

-- Tabela Venda
CREATE TABLE Venda (
    VendaID INT PRIMARY KEY,
    DataVenda DATETIME NOT NULL,
    ValorTotal DECIMAL(10, 2) NOT NULL,
    MetodoPagamento VARCHAR(20),
    ClienteID INT,
    ColaboradorID INT,
    FOREIGN KEY (ClienteID) REFERENCES Cliente(ClienteID)
        ON DELETE SET NULL ON UPDATE CASCADE,
    FOREIGN KEY (ColaboradorID) REFERENCES Colaborador(ColaboradorID)
        ON DELETE SET NULL ON UPDATE CASCADE
);

-- Tabela DetalhesVenda
CREATE TABLE DetalhesVenda (
    VendaID INT,
    CódigoProduto INT,
    Quantidade INT NOT NULL,
    Subtotal DECIMAL(10, 2) NOT NULL,
    PRIMARY KEY (VendaID, CódigoProduto),
    FOREIGN KEY (VendaID) REFERENCES Venda(VendaID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (CódigoProduto) REFERENCES Produto(CódigoProduto)
        ON DELETE CASCADE ON UPDATE CASCADE
);

-- Tabela Estoque
CREATE TABLE Estoque (
    CódigoProduto INT PRIMARY KEY,
    QuantidadeMinima INT NOT NULL,
    AlertaEstoque BOOLEAN NOT NULL DEFAULT FALSE,
    FOREIGN KEY (CódigoProduto) REFERENCES Produto(CódigoProduto)
        ON DELETE CASCADE ON UPDATE CASCADE
);

-- Índices para otimização de consultas
CREATE INDEX idx_FornecedorID ON Produto(FornecedorID);
CREATE INDEX idx_ClienteID ON Venda(ClienteID);
CREATE INDEX idx_ColaboradorID ON Venda(ColaboradorID);
CREATE INDEX idx_CódigoProduto ON DetalhesVenda(CódigoProduto);
CREATE INDEX idx_CódigoProduto_Estoque ON Estoque(CódigoProduto);
